version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-1
    IMAGE_REPO: myapp

phases:
  pre_build:
    commands:
      - echo "Login to ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 084828589246.dkr.ecr.$AWS_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO:$COMMIT_HASH-live .
      - docker tag $IMAGE_REPO:$COMMIT_HASH-live 084828589246.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO:$COMMIT_HASH-live
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 084828589246.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO:$COMMIT_HASH-live
artifacts:
  files:
    - appspec.yml
    - scripts/*
