version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-1
    ACCOUNT_ID: "084828589246"
    IMAGE_REPO: cicd-test-ecr

phases:
  pre_build:
    commands:
      - 'set -euo pipefail'
      - 'echo === DEBUG: aws/identity/docker ==='
      - 'aws --version'
      - 'docker version || true'
      - 'echo STS: $(aws sts get-caller-identity --query Arn --output text --region ${AWS_REGION})'
      - 'aws ecr describe-repositories --repository-names ${IMAGE_REPO} --region ${AWS_REGION}'
      - 'export REGISTRY=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com'
      - 'echo Login to ${REGISTRY}'
      - 'aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REGISTRY}'

  build:
    commands:
      - 'export COMMIT_HASH=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)'
      - 'echo Building ${IMAGE_REPO}:${COMMIT_HASH}-live'
      - 'docker build -t ${IMAGE_REPO}:${COMMIT_HASH}-live .'
      - 'docker tag ${IMAGE_REPO}:${COMMIT_HASH}-live ${REGISTRY}/${IMAGE_REPO}:${COMMIT_HASH}-live'

  post_build:
    commands:
      - 'echo Pushing ${REGISTRY}/${IMAGE_REPO}:${COMMIT_HASH}-live'
      - 'docker push ${REGISTRY}/${IMAGE_REPO}:${COMMIT_HASH}-live'

artifacts:
  files:
    - 'appspec.yml'
    - 'scripts/**'
